version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db2
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:
  minio_data:

networks:
  backend:
